FROM python:3.9-alpine

WORKDIR /myfinance

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /myfinance

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . /myfinance

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]