# Generated by Django 3.2.6 on 2021-08-15 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.category'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_of_op',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 22, 19, 0, 162246)),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.type'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.type'),
        ),
    ]
