# Generated by Django 3.2.6 on 2021-08-15 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210815_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('expense', 'expense'), ('profit', 'profit')], max_length=7),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_of_op',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 22, 27, 3, 707620)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('expense', 'expense'), ('profit', 'profit')], max_length=7),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
