# Generated by Django 3.2.6 on 2022-01-22 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210815_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type',
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_of_op',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 22, 34, 1, 260162)),
        ),
    ]
