# Generated by Django 3.2.6 on 2021-01-22 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210815_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['date_of_op']},
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_of_op',
            field=models.DateField(default=datetime.datetime(2022, 1, 22, 0, 18, 44, 79187)),
        ),
    ]
